spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql:localhost:3306/soil
    driver-class-name: com.mysql.jdbc.Driver
    data-username: lxtest
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true